config/routes.rb
Rails.application.routes.draw do

  resources :contents
  devise_for :users
  
  root 'pages#home'
  get 'about' => 'pages#about'

end

app/models/content.rb
class Content < ActiveRecord::Base
	belongs_to :user

	has_attached_file :cover, styles: { medium: "300x>", thumb: "100x>" }
  	validates_attachment_content_type :cover, content_type: /\Aimage\/.*\z/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :contents
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
    devise_parameter_sanitizer.for(:account_update) << :name
  end

end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  before_action :set_content, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :check_user, only: [:edit, :update, :destroy]

  def index
    @contents = Content.all
  end

  def show
  end

  def new
    @content = current_user.contents.build
  end

  def edit
  end

  def create
    @content = current_user.contents.build(content_params)

    respond_to do |format|
      if @content.save
        format.html { redirect_to @content, notice: 'Content was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /contents/1
  # PATCH/PUT /contents/1.json
  def update
    respond_to do |format|
      if @content.update(content_params)
        format.html { redirect_to @content, notice: 'Content was successfully updated.' }
        format.json { render :show, status: :ok, location: @content }
      else
        format.html { render :edit }
        format.json { render json: @content.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contents/1
  # DELETE /contents/1.json
  def destroy
    @content.destroy
    respond_to do |format|
      format.html { redirect_to contents_url, notice: 'Content was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_content
      @content = Content.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def content_params
      params.require(:content).permit(:titolo, :descrizione, :price, :cover)
    end

    def check_user
      if current_user != @content.user
        redirect_to root_url, alert: "Non puoi accedere a questa pagina"   
      end
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/contents/_form.html.erb
<%= form_for @content, html: { multipart: true } do |f| %>
  <% if @content.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@content.errors.count, "error") %> prohibited this content from being saved:</h2>

      <ul>
      <% @content.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :titolo %><br>
    <%= f.text_field :titolo %>
  </div>
  <div class="field">
    <%= f.label :descrizione %><br>
    <%= f.text_area :descrizione %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>

  <div class="field">
    <%= f.label :cover %><br>
    <%= f.file_field :cover %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contents/edit.html.erb
<h1>Editing Content</h1>

<%= render 'form' %>

<%= link_to 'Show', @content %> |
<%= link_to 'Back', contents_path %>

app/views/contents/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Contents</h1>

<table>
  <thead>
    <tr>
      <th>Immagine</th>
      <th>Titolo</th>
      <th>Descrizione</th>
      <th>Utente</th>
      <th>Prezzo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contents.each do |content| %>
      <tr>
        <td><%= image_tag content.cover.url(:thumb) %><td>
        <td><%= content.titolo %></td>
        <td><%= content.descrizione %></td>
        <td><%= content.user.name %></td>
        <td><%= content.price %></td>
        <td><%= link_to 'Show', content %></td>
        <% if content.user == current_user %>
          <td><%= link_to 'Edit', edit_content_path(content) %></td>
          <td><%= link_to 'Destroy', content, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Content', new_content_path %>

app/views/contents/new.html.erb
<h1>New Content</h1>

<%= render 'form' %>

<%= link_to 'Back', contents_path %>

app/views/contents/show.html.erb
<p id="notice"><%= notice %></p>

<%= image_tag @content.cover.url(:medium) %>

<p>
  <strong>Titolo:</strong>
  <%= @content.titolo %>
</p>

<p>
  <strong>Descrizione:</strong>
  <%= @content.descrizione %>
</p>

<p>
  <strong>Price:</strong>
  <%= @content.price %>
</p>

<% if @content.user == current_user %>
	<%= link_to 'Edit', edit_content_path(@content) %> |
<% end %>
<%= link_to 'Back', contents_path %>

app/views/layouts/_footer.html.erb
<footer class="page-footer">
  <div class="container">
    <div class="row">
      <div class="col l6 s12">
        <h5 class="white-text">Footer Content</h5>
        <p class="grey-text text-lighten-4">You can use rows and columns here to organize your footer content.</p>
      </div>
      <div class="col l4 offset-l2 s12">
        <h5 class="white-text">Links</h5>
        <ul>
          <li><a class="grey-text text-lighten-3" href="#!">Link 1</a></li>
          <li><a class="grey-text text-lighten-3" href="#!">Link 2</a></li>
          <li><a class="grey-text text-lighten-3" href="#!">Link 3</a></li>
          <li><a class="grey-text text-lighten-3" href="#!">Link 4</a></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="footer-copyright">
    <div class="container">
    © 2014 Copyright Text
    <%= link_to "About", about_path, class:"grey-text text-lighten-4 right" %>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar-fixed">
	<nav class="orange lighten-1">
		<div class="container nav-wrapper">
		  <%= link_to "onFood", root_path, class: "brand-logo" %>
		  <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
		  <ul class="right hide-on-med-and-down">
		  	<% if user_signed_in? %>
		  		<li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
		  	<% else %>
		  		<li><%= link_to "Accedi", new_user_session_path %></li>
		  		<li><%= link_to "Registrati", new_user_registration_path %></li>
		  	<% end %>

		  </ul>
		  <ul class="side-nav" id="mobile-demo">
		  	<% if user_signed_in? %>
		  		<li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
		  	<% else %>
		  		<li><%= link_to "Accedi", new_user_session_path %></li>
		  		<li><%= link_to "Registrati", new_user_registration_path %></li>
		  	<% end %>
		  </ul>
		</div>
	</nav>
</header>
          

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>OnFood</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

   <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
</head>
<body>

	<%= render "layouts/header" %> 
	<p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

	<main class="container">
		<%= yield %>
	</main>
	<%= render "layouts/footer" %> 

</body>

	<script>
		$(".button-collapse").sideNav();
	</script>

</html>

app/views/pages/about.html.erb
<h1>Pagina about</h1>

app/views/pages/home.html.erb
<h1>Pages#home</h1>